apiVersion: v1
kind: ConfigMap
metadata:
  name: event-manager-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/planify"
  SPRING_DATASOURCE_USERNAME: "planify"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
