apiVersion: v1
kind: ConfigMap
metadata:
  name: event-manager-config
data:
  SPRING_DATASOURCE_URL: {{ .Values.config.database.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.database.username | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafka.bootstrapServers | quote }}