apiVersion: v1
kind: Service
metadata:
  name: event-manager-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: event-manager-service
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}